### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by rembo10** [headphones/cans#7]
Hey - just wanted to get in touch because I've been working on a javascript rewrite of headphones. Might be better to join forces?

**Comment by pnovotnak** [comment]
Yes! I'd love to join forces!

What's your stack? I'd be fine with ditching golang, there are way more
people that know js. Golang is just my hammer right now ;-)

**Comment by pnovotnak** [comment]
However, I don't mean to be dismissive of my own choices. I think go would be a more ideal choice (in theory) here since it's got parallelism that node.js doesn't have. However, I'm happy to yield and make a pure javascript app if it means we can work together. Are you in the USA? Pacific Northwest? I'd love to sit down and have a beer / coffee / ??? and chat! My email is on my profile page

**Comment by rembo10** [comment]
I wouldn't be opposed to using go. But I haven't used it before so I'd have
to learn it.

While I was testing it it was just node on the backend and angular on the
frontend.

I'm also cutting out a ton of cruft - so the backend would just basically
be an api. And I was going to cut out all the business of mirroring the
musicbrainz db locally.

There's a bit more but I just wanted to get in touch just to give you a
heads up so we didn't duplicate effort

**Comment by rohanpandula** [comment]
Im excited to see what you guys can do together!

**Comment by pnovotnak** [comment]
Ok, should we split our client-side code out into a repo? I think that'd be a good start. Then we can work on that together no matter what the backend code looks like.

**Comment by pnovotnak** [comment]
Thanks @rohanpandula, me too!

**Comment by JamieMagee** [comment]
I am also interested in helping with this going forward.

I would not suggest splitting out the client-side code into another repo. I can't envisage any end users just wanting to run the backend, and it'll just make it more difficult for developers to work on the project - you'd have to make sure two repos are up to date, whereas if it's all in one repo the master branch should always be stable and frontend and backend should be compatible.

**Comment by pnovotnak** [comment]
@JamieMagee Didn't even think about that. Good call. Do you know Angular? Bulk of the code is going to be client-side so that's probably a good place to focus efforts. My front-end is... Rusty :)

Otherwise, it's whatever you want to work on dude! I've added you as a collaborator, lmk if there's anything you don't have that I do.

Some ideas I've had are;
- UI / UX design. It'd be cool to see something that's easier and more efficient to use
- Filesystem stuff, eg. Scanning directories, watching torrent folders, music fingerprinting, tagging...
- Usenet support
- Any of the longer-term goals I noted on the readme are things are things I want to get done at some point

**Comment by JamieMagee** [comment]
Unfortunately I'm not an Angular developer - I'm a Java dev by day - but I'm willing to give it a shot and learn.

I'll get stuck in with yeoman and angular and see where I get to :smile:

**Comment by rembo10** [comment]
I have a v2 repo in my github where I was tinkering with the node backend
if you want to take a look

**Comment by maxcore** [comment]
i am already fan !

**Comment by pnovotnak** [comment]
@rembo10 I think you're right, just the DB, file and torrent management, and odds and ends other bits live in the backend. All the other stuff should be cross site requests directly to APIs. POSTs to the backend to store Artist / Release information, track torrent status, etc.

Some updates on Golang backend progress here:

I was working on WhatCD and transmission in this repo since we only need a couple functions from each, but I decided that was not a good approach for either us or the community. I found a library for each and did a cursory audit of each for our use, but they aren't of very high quality.

The [semi-official WhatCD golang client](https://github.com/kdvh/whatapi) has one particular issue that makes it impossible for us to use right now. It calls log.Fatal() on error. I've got a pull request pending to remove all instances. Once it's merged it should work, but I think it might be better just to skip it entirely and do everything from the browser since there is a [JS repo with a lot of stars and only a few forks](https://github.com/deoxxa/whatcd). As for transmission, the story is similar; https://github.com/longnguyen11288/go-transmission I'm a little bit concerned that there are more forks than stars (!). We could use one of the newer forks (but which one?) Or just integrate a little [reverse proxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy) that proxies requests to transmission from the client and vendor the [JS client functions from the transmission core](https://trac.transmissionbt.com/browser/branches/1.5x/web/javascript/transmission.remote.js). I think we still need to integrate transmission server-side though, to decide when to move stuff and where to move it from. What do y'all think about that? I can probably mock up a simple transmission library the next time I get the chance to work on the app, otherwise that's low hanging fruit for someone else who want's to contribute server-side.

I'm backing off the client side code for now, since it seems like we have a lot of people around who know JS but few who know Golang. However, if nobody steps up to do the client I'll start working on that after I get transmission working. My personal goal is to have a working prototype by June that can:
- Search for artists and releases
- Match the artist/release to a torrent
- Queue the torrent in transmission
- Move the completed files from downloads to a single destination

**Comment by rembo10** [comment]
You might want to just hold up a bit so we can collaborate. I've been
working on stuff on my end (but I've been using node - since there are a
lot of libraries that we can use). Go might be a better choice though, not
100% sure yet.

I just like the idea of having javascript everywhere. I think it would make
it easier for other people to contribute (plus I like the ecosystem,
especially now that a lot of front end packages are available through npm
using browserify).

Should we use Angular2? It's in beta now.

I'm still trying to figure out the division of labor between server and
client. I think a lot of it still needs to be backend (searching, updating,
etc) since it'll have to run in the background no matter what.

But stuff like pulling artist images, pulling artist info, etc., can all be
done through the browser and we can cache that info...... should eliminate
a lot of unneccessary calls.

Anyways, working on it now - I should be able to give you a bit more info
on the roadmap in a few days

**Comment by rembo10** [comment]
There is also [Aurelia](http://aurelia.io) for the frontend which looks nice

**Comment by pnovotnak** [comment]
I'd love to collaborate! Free time is pretty hard for me to find/wildly unpredictable, however, and I'd like to get working on this ... I want to start using it :). More consistent communication from you would help me more effectively utilize the time I'm able to work on this with you. The only stuff I've seen from you is on this thread, which makes it really hard to figure out what I should devote my time to developing.

I've been trying to create issues and things in this particular organization so we can know where things are and where they are going. When we gain some steam and have more developers working together it will become crucial to organize ourselves so that we can manage development as a collective, so we might as well start now. Personally, I would prefer that work is done in a group repository so my contributions aren't tied to a single person's reputation. 

However, Headphones is most definitely your "brand", and I absolutely respect that. If you want this to be your brainchild, I'll bug off and work on this under another banner; I don't want to step on your toes. I think this is such a great idea, though, and I'd love to keep collaborating and contributing. Just let me know if you would like for me to keep committing.

**Comment by rembo10** [comment]
Yeah I get that. Sorry I've been pretty MIA lately; things have been hectic
on my end as well.

But since I've been working on the original version for so long, I sort of
have a good idea of how everything should work together, just from all the
mistakes I've made in the original design..... so I think if you want me to
take the helm that would probably make your life much easier :)

I'm going to start pushing commits soon, just wanted to test out different
frameworks and design ideas before I made anything too public.

Oh, how are your design skills btw? That's the area I'm probably lacking in
the most and it would be good to bounce ideas off someone

Cheers

**Comment by pnovotnak** [comment]
I think our vectors are irreconcilable, so for fear of dividing the community and appropriating your brand, I'm going to bow out.

Best of luck! Let me know when the beta is out so I can test ;-)

**Comment by rembo10** [comment]
How do you figure?

**Comment by satreix** [comment]
@pnovotnak I really like the way you were going with that project. Golang + angular would have been a great choice for an efficient and **portable** headphones rewrite. Is it dead in the egg or are you still planning on working on the project?

@rembo10 I figured out you are pretty busy and do not give that much time lately on headphone (all the PR keep on stacking). Would you be ready to let some of us take part of the reviewing process?

What I would like to see is the following: 
- move the headphones home over here : headphones/headphones
  - the point being to have more reviewer able to merge PR more frequently
  - constitue a headphone team to discuss design and going forward with the project
- keep up the work on **cans**
  - the easy win would be to rewrite small parts of headphones in go (search, torrent, newsgroup) and then build upon those building blocks to release a full fledge go product that can compile and be distributed to various platforms.

@JamieMagee, with what happened with pip on rembo10/headphones/pull/2438, how do you feel about this.

PS: I am much much more confident in python and golang than the whole js env. Plus would really like to avoid going the node way for this project.

**Comment by rembo10** [comment]
Hey, yeah sorry I've been MIA. I finally got around to looking at golang
and it is awesome. So I've spent the past few weeks learning it and
figuring out the best way to organize everything. That's why I haven't had
much time to look at the pull requests.

I could definitely use some help in terms of architecture just so the new
project gets off on the right foot.

As for frontend, I was looking at angular2 and i like it but what do you
guys think about cycle.js or elm?

**Comment by satreix** [comment]
> I finally got around to looking at golang and it is awesome.  That's why I haven't had much time to look at the pull requests.

I guess we do not want to rush out the golang rewrite. Easy PR on headphones should come first.

> As for frontend, I was looking at angular2 and i like it but what do you guys think about cycle.js or elm?

I did not know them, that is not a good point. We do not want to base our shinny new rewrite on a _small_ javascript frontend framework. That is why I would norrow the choice to Angular2 or React.

@rembo10 would you be ready to move headphone under a new roof (headphone/headphones) and let some of us take part of the reviewing process?
